version: '3.9'

services:
  strapi:
    build: .
    container_name: strapi
    restart: always
    ports:
      - '1337:1337'
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi123
      JWT_SECRET: mySuperSecretKey
      APP_KEYS: appKey1,appKey2
      API_TOKEN_SALT: superSalt
      ADMIN_JWT_SECRET: adminSecret
      NODE_ENV: production
    volumes:
      - ./public:/app/public
      - ./uploads:/app/uploads
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi123
      POSTGRES_DB: strapi
    volumes:
      - strapi-data:/var/lib/postgresql/data

volumes:
  strapi-data:
